### PR TITLE
Fix AppStateActiveOnce event listener

### PR DESCRIPTION
**Pull request by logangouget**
In some cases, browser is closed before handling an AppState change, event is never triggered

### CODE REVIEW

**Comment by phuongwd** [comment]
@logangouget 
Very interesting!
It would be cool if you add the steps for reproduce or video, gif

**Comment by logangouget** [comment]
Just found that it happens only when redirectUrl parameter is undefined and browser is closed directly (in a logout scenario for example)

**Comment by jdnichollsc** [comment]
@logangouget thanks for your help! can you revert changes from yarn.lock please?

**Comment by jdnichollsc** [comment]
Thanks for your help!

**Comment by zanechua** [comment]
@jdnichollsc Did you mean for the `yarn.lock` file to get deleted? You asked for reversion of changes for `yarn.lock` but now it seems like the entire lock file has been removed.

**Comment by jdnichollsc** [comment]
No problem, I merged that change, I'm fixing some issues before to publish a new version, hope to finish that today

**Pull request merged**
