### PR TITLE
Fix EventBusException on Android

### PR DESCRIPTION
**Pull request by Almouro**
Similar issue as https://github.com/proyecto26/react-native-inappbrowser/pull/45
Calling the `open` function twice could trigger the `EventBus.getDefault().register(this);` twice which would trigger:

```
org.greenrobot.eventbus.EventBusException: Subscriber class com.proyecto26.inappbrowser.RNInAppBrowser already registered to event
```

This makes sure we don't register again the browser instance

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Excellent mate!
Can you add you as a contributor from the README please? 👍

**Comment by Almouro** [comment]
@jdnichollsc Haha thanks! It's done :)

**Comment by jdnichollsc** [comment]
@Almouro please don't update the version of the package, I want to include this change as part of version 2.0

**Comment by Almouro** [comment]
@jdnichollsc whoopsy, fixed now 👍

**Comment by jdnichollsc** [comment]
Excellent, thanks for your help! 🥇

**Pull request merged**
