### PR TITLE
Add `@ReactModule` annotation

### PR DESCRIPTION
**Pull request by janicduplessis**
Add `@ReactModule` annotation, this will eventually be used by TurboModules annotation processor.

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hi @janicduplessis,
So it looks like we need to revert this change? https://github.com/proyecto26/react-native-inappbrowser/commit/dcbfaef49fa04fdabc281cd2c61124a11c6a7d29#diff-7ae5a9093507568eabbf35c3b0665732

What do you think? 🤔

**Comment by janicduplessis** [comment]
@jdnichollsc Hmm why do we need to revert this? Should not be related to this PR.

**Comment by jdnichollsc** [comment]
So is `com.facebook.react.module.annotations` already included? 🤔

**Comment by janicduplessis** [comment]
@jdnichollsc Yes it is included in react native already, there is no need to add dependencies.

**Comment by jdnichollsc** [comment]
@janicduplessis thanks for your help mate, Do you know any link to see the documentation of this? 👍

**Comment by janicduplessis** [comment]
There is not much documentation yet except https://github.com/react-native-community/discussions-and-proposals/issues/40. Basically the annotation allows generating some info about the native module (mostly the name) that can be used by `TurboReactPackage`. The annotation was added a long time ago so there's no issue with backwards compatibility.

**Comment by janicduplessis** [comment]
Also some info in this twitter thread https://twitter.com/janicduplessis/status/1157172268495179776

**Comment by jdnichollsc** [comment]
Hey mate, thanks for your help! In order to merge this PR, how can we avoid an issue like this? https://github.com/react-native-community/async-storage/issues/153

**Comment by janicduplessis** [comment]
Hmm I think this might just happen as a result of a weird issue when upgrading. It is mentionned in the issue that it does not happen on a new project.

**Comment by jdnichollsc** [comment]
Thanks for your help! 👍

**Pull request merged**
