### PR TITLE
Fix invalid scheme with iOS 14.5

### LINKED ISSUE #256: Exception: The provided scheme is not valid iOS 14.5
### Make sure to check the demo app(s) for sample usage 
Checked

### Make sure to check the existing issues in this repository 
Checked, couldn't find any issue related to this one

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS 14.5 only
- both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.13.1
- Plugin(s): 
```
"dependencies": {
    "@apollo/client": "^3.3.15",
    "@react-keycloak/native": "^0.5.2",
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "apollo-upload-client": "^14.1.3",
    "graphql": "^15.5.0",
    "i18next": "^20.2.2",
    "ramda": "^0.27.1",
    "react": "^17.0.2",
    "react-i18next": "^11.8.13",
    "react-native": "^0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-sensitive-info": "^6.0.0-alpha.9"
  },
  "devDependencies": {
    "@babel/core": "^7.13.16",
    "@babel/runtime": "^7.13.17",
    "@graphql-codegen/cli": "^1.21.4",
    "@graphql-codegen/fragment-matcher": "^2.0.1",
    "@graphql-codegen/introspection": "^1.18.2",
    "@graphql-codegen/typed-document-node": "^1.18.5",
    "@graphql-codegen/typescript": "^1.22.0",
    "@graphql-codegen/typescript-apollo-client-helpers": "^1.1.5",
    "@graphql-codegen/typescript-operations": "^1.17.16",
    "@graphql-codegen/typescript-react-apollo": "^2.2.4",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/ramda": "^0.27.40",
    "@types/react-native": "^0.64.4",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "concurrently": "^6.0.2",
    "eslint": "^7.25.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.2.4"
  },
```
### Please, tell us how to recreate the issue in as much detail as possible. 
I am using react-native-keycloak and opened the issue on that repo too https://github.com/react-keycloak/react-native-keycloak/issues/38, but most likely it's related to the Inappbrowser.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
err

### PR DESCRIPTION
**Pull request by SimonIT**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/master/CONTRIBUTING.md#pull-request-process.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?

Exception with invalid scheme is thrown

## What is the new behavior?

The scheme will be escaped by default

Fixes/Implements/Closes #256

I tried testing this change with the example but there occurred just more errors. I fixed the flipper and babbel one and then gave up.
I hope everything will work. I'm not very familiar with iOS so don't bash me if I made something wrong. I just need the fix.

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hello mate, thanks for your collaboration

Do you know if this change is a breaking change for old versions of iOS? :)

**Comment by SimonIT** [comment]
I just researched the iOS version requirement for react native: iOS 7.0+ is required since 0.14.0 which came out 2015 (source facebook/react-native@e2841c05b4bc67aad90854c7013b278ca4abe03a). So I would say, that this is pretty safe

**Comment by jdnichollsc** [comment]
Awesome, thanks for letting me know! @maoapp is going to help us with a new release including these changes :)

**Comment by waltershub** [comment]
@jdnichollsc why isn't this merged yet

**Comment by jdnichollsc** [comment]
I'm busy, maybe @maoapp too 🙂
Let me confirm you 👍

**Comment by exception** [comment]
Similar issue resolved here https://github.com/auth0/react-native-auth0/pull/369/files, this was a breaking change with iOS 14.5

**Comment by hszouszcz** [comment]
Let me gently poke you one more time (:

**Comment by ftlno** [comment]
Any chance of this getting merged soon?

**Comment by janicduplessis** [comment]
I think using `[[NSURL alloc] initWithString:redirectURL].scheme;` to extract only the scheme part from the URL would be a better fix, like what was done in https://github.com/auth0/react-native-auth0/pull/369/files

**Comment by jdnichollsc** [comment]
@SimonIT what do you think? 🙂

**Comment by SimonIT** [comment]
If it works, why not. I personally don't see the benefit of it

**Comment by SimonIT** [comment]
Just tried it myself, seem to work fine

**Comment by janicduplessis** [comment]
The api expects only the scheme part of the URL so I think it is better to do that instead of encoding the slashes to bypass the validation check.

**Comment by jdnichollsc** [comment]
Agree! Please let me know folks <3
PD: In the meantime, do you know if this issue is fixed by using `encodeURIComponent('my-scheme://')` from JS side? 🤔

**Comment by SimonIT** [comment]
I actually don't know and I can't try it, because I'm not directly using this lib. Another lib I'm using is using this lib. That's why this fix is so important for me.
By the way, I updated it to only use the scheme

**Comment by PhilippBurgk** [comment]
If someone has a direct dependency and needs this fix, you can do the following:

Change the dependency to the commit hash.
`"react-native-inappbrowser-reborn": "https://github.com/SimonIT/react-native-inappbrowser#b35ef11f48c072971ec61049dc1370678db2dac1",`

**Comment by mocanSergiu666** [comment]
> Agree! Please let me know folks <3
> PD: In the meantime, do you know if this issue is fixed by using `encodeURIComponent('my-scheme://')` from JS side? 🤔

I tried it, but it doesn't make the redirect back, even though it doesn't crash :)

**Comment by zachnicoll** [comment]
Any updates on getting this merged?

**Comment by akubara** [comment]
> Agree! Please let me know folks <3
> PD: In the meantime, do you know if this issue is fixed by using `encodeURIComponent('my-scheme://')` from JS side? thinking

Yep, `Platform.OS === 'android' ? deeplinkUri : encodeURIComponent(redirectUri),` works on ios 14.5+

**Comment by rainyer** [comment]
> Any updates on getting this merged?

+1

**Comment by jdnichollsc** [comment]
I'm going to publish this change today, thanks folks! <3

**Comment by markl-vesper** [comment]
I'm getting this error on 3.6.3

**Pull request merged**
