### PR TITLE
Remove deprecated `removeEventListener()` calls

### LINKED ISSUE #296: RN v0.65: Warnings pertaining deprecated usage of event listeners
### Which platform(s) does your issue occur on?
- iOS/Android/Both: Both
- iOS/Android versions: all
- emulator or device. What type of device? Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.0
- Plugin(s): 
-- RN: 0.65.1
-- InAppBrowser: 3.6.3

### Please, tell us how to recreate the issue in as much detail as possible. 
With the advent of RN v0.65, they changed the way you set up event listeners and throw warnings that "calling `removeListener()` has been deprecated" (as per this commit https://github.com/facebook/react-native/commit/035718ba97bb44c68f2a4ccdd95e537e3d28690c#diff-53ad587a2f77ca63b6940dbf0026a101e3874de1858e058d217a8f4c04d4987e). See the following screenshot:

inappbrowser-screenshot copy

I would've just done and submitted a PR, but the CONTRIBUTING guidelines told me to "first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change." 😅

### PR DESCRIPTION
**Pull request by TheWirv**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/main/CONTRIBUTING.md#pull-request-process.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?

For React Native's `Linking` and `AppState` APIs, the deprecated `removeEventListener()` calls had been used before.

## What is the new behavior?

Both `Linking.addEventListener()` and `AppState.addEventListener()` return an event subscription object containing a corresponding `remove()` method. They are being used in `utils.js` now.

Fixes/Implements/Closes #296.
No breaking changes

@jdnichollsc I am a TypeScript person and have never worked with flow before. Please check the flow types whether they are still correct.

### CODE REVIEW

**Comment by radko93** [comment]
@jdnichollsc  This PR is not backwards compatible (at least not all the way to older versions), but it is possible. I've made a similar PR recently https://github.com/AgoraIO-Community/react-native-agora/pull/414/files

**Comment by mr-rick** [comment]
I have tested your latest commit and I'm getting these errors...

`I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 1
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 1
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 1
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 1
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@97b629a[MainActivity]: ViewPostIme pointer 1`

A quick google search says..... "The reason is because you miss to set listener to your button."

btn.setOnClickListener(this);

I'm on react native 66.3

**Comment by TheWirv** [comment]
No, absolutely not, sorry. :/

**Comment by jdnichollsc** [comment]
No problem, let me try and thanks for your help mate! <3

**Comment by ajaxjiang96** [comment]
Is their a release plan for this patch?

**Comment by jdnichollsc** [comment]
I'm creating a new Release 3.7.0, stay tunned! <3

**Pull request merged**
