### PR TITLE
Update podspec for install using pod file

### PR DESCRIPTION
**Pull request by plamworapot**

### CODE REVIEW

**Comment by jdnichollsc** [comment]
I don't know, I have issues using pods with React Native dependency... It's better to open Xcode, import the .xcodeproj file from `./node-modules/react-native-inappbrowser-reborn/ios` into **Libraries** folder of your project and later add this library into **Linked Frameworks and Libraries** from the general section of Xcode

**Comment by adammcarth** [comment]
@jdnichollsc At the very least, you should remove the current `.podspec` file (which is currently broken without @plamworapot's changes).

> I don't know, I have issues using pods with React Native as dependency... It's better to open Xcode, import the .xcodeproj file [...]

I strongly disagree with this, however. I think you should give users the option to install this module using Cocoa Pods. Almost every reputable React Native Module package has the option of installing it this way, and to not offer this because you don't know how to configure it in your own projects is kind of a... _bizarre_ reason to me?

Cocoa Pods is a much cleaner way of managing dependancies for iOS, and for the time being we've had to manually modify your `.podspec` file to make it not crash our build process.

Thank you for the pull request @plamworapot - we actually forgot to add the `exclude_files` flag in our own internal patch 😋.

**Comment by adammcarth** [comment]
Thanks @jdnichollsc :)

**Comment by jdnichollsc** [comment]
You're welcome, but I need to publish a new version from npm. Can you @plamworapot give me your email please to add you as collaborator from the README?

**Comment by adammcarth** [comment]
Hold up two seconds @jdnichollsc.

I've just tested the latest master and I'm getting a build error after running `pod install` with @plamworapot's patch.

Anyone have any ideas? I can test this tonight after work.

Error

**Comment by adammcarth** [comment]
I can't see any differences between our fix and the current one, besides the fact that the `.podspec` file was moved back one directory.

**Comment by jdnichollsc** [comment]
Can you remove the cache and try again please?

**Comment by adammcarth** [comment]
Shutting down Xcode and restarting it fixed the issue for me.  A bit of a strange one - I wonder if the invalid podspec file threw it off?

Anyway, all seems well. I'm just going to submit one little bug fix in the podspec file though.

**Comment by jdnichollsc** [comment]
Can you guys share your podfile to see the configuration please? 👍

**Comment by adammcarth** [comment]
@jdnichollsc I can't share the specific `.podspec` file (it's a commercial project). But here's one I've just made that _would_ work:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'your_app_name' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # React Native Dependancies
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  # React Native In App Browser Library
  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

Note the final `post_install` code which removes "React" after pod installation is complete since it's already installed in your Xcode project. Failing to have this will give you duplicate symbol errors at compile time.

FYI, the reason we include React Native earlier in the Podfile (before removing it) is because the third party modules require it as a dependancy during installation.

Let me know how you go,

Adam.

**Comment by jdnichollsc** [comment]
Ohh I understand... but after install a lot of plugins, I removed the same configuration that you have with React and removing it from each plugin, check my old podfile  https://gist.github.com/jdnichollsc/a604fdbb2f6205607cb65d1964a77518

**Pull request merged**
