### PR TITLE
Fix start animation not visible

### PR DESCRIPTION
**Pull request by miktolon**
This is possible solution to #52.

Start animation, provided by user and built with setStartAnimations, seem to not be visible with startActivity.
This can however be made visible by providing it as options bundle when starting activity.

Applicable bundle for this is already made as startAnimationBundle when CustomTabsIntent is built.

See:
https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#startAnimationBundle
https://developer.android.com/reference/android/app/ActivityOptions.html

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hi mate,

Let me try, in the meantime can you add you as a contributor from the README of the project? 👍

**Comment by miktolon** [comment]
@jdnichollsc Added

**Comment by jdnichollsc** [comment]
mmm I can't see any difference testing from my Android device, also testing with a overridePendingTransition:
```
currentActivity.startActivity(
        ChromeTabsManagerActivity.createStartIntent(currentActivity, intent), customTabsIntent.startAnimationBundle);
currentActivity.overridePendingTransition(
  resolveAnimationIdentifierIfNeeded(context, "slide_in_right"),
  resolveAnimationIdentifierIfNeeded(context, "slide_out_left")
);
```
What about you?

**Comment by jdnichollsc** [comment]
Nevermind, works perfect!!

**Comment by miktolon** [comment]
Can you see opacity animation working in your device? I didn't get it visible with this minor modification, but could see slide animation working by testing with different animation speeds and directions.

**Comment by jdnichollsc** [comment]
@miktolon can you attach your animations to debug here? :)

**Comment by miktolon** [comment]
I used the example ones :) only modified attributes on those for testing.

**Pull request merged**
