### PR TITLE
Update index.d.ts isAvailable class method return type

### PR DESCRIPTION
**Pull request by petekp**
Updated typing to correspond with the update to make `isAvailable` return a boolean: https://github.com/proyecto26/react-native-inappbrowser/commit/c3a95da85c441dd026c435caf28499fbc8a1de7d

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hi petekp, please fix to `Promise<boolean>`

**Comment by petekp** [comment]
@jdnichollsc Oops, fixed :)

**Comment by jdnichollsc** [comment]
Sorry, can you add you as a contributor from the README please?

**Comment by petekp** [comment]
@jdnichollsc Done!

**Pull request merged**
