### PR TITLE
Fix react and react-native deps

### PR DESCRIPTION
**Pull request by friederbluemle**
Use fixed versions for `react` and `react-native`.

One version of `react-native` is always tightly coupled with exactly one version of `react`. They can't go out of sync, or things will likely break.

### CODE REVIEW

**Comment by jdnichollsc** [comment]
This package don't need `react` as dependency, and for that reason don't care the version used for React Native 🙂

**Comment by jdnichollsc** [comment]
On the other hand we're using gitflow now, so please create PR to `develop` branch 👍

**Comment by friederbluemle** [comment]
I agree there is no _direct_ dependency on `react` in the source code. But there is one (of course) on `react-native`. And `react-native` has a peer dependency on `react`. Without declaring it as a dev dependency, it would be missing sources when resolving types located in the `react` package (during development).

**Comment by friederbluemle** [comment]
I've changed the base branch and rebased onto `develop`. 👍

**Comment by jdnichollsc** [comment]
I mean, what script of the package requires that dependency? We're using the example project to debug the plugin and we don't need that :)

**Comment by friederbluemle** [comment]
I can remove it if you really want to.. It will cause a warning when installing dependencies:

```
warning " > react-native@0.60.0" has unmet peer dependency "react@16.8.6".
```

I have a bunch of other branches locally, including one related to CI which builds the library code in isolation (no other code required), to be able to detect and fix issues. Having a complete description of the project dependency model be one of the prerequisites.

**Comment by friederbluemle** [comment]
Hi @jdnichollsc - Are you no longer interested in the fixes here?

**Comment by jdnichollsc** [comment]
I compared other repositories of the community and it's ok without include react as dependency for non UI plugins like this:
- https://github.com/react-native-community/react-native-netinfo/blob/master/package.json#L52
But thanks!

**Comment by jdnichollsc** [comment]
@friederbluemle if you want, please fix the merge issues of these devDependencies and I can merge that

**Comment by friederbluemle** [comment]
@jdnicholls Sure thing! Can you please reopen the PR, and I'll push the updated branch with conflicts resolved.

**Comment by friederbluemle** [comment]
Thanks! Updated 👍

**Comment by jdnichollsc** [comment]
Thanks to you!

**Pull request merged**
