### PR TITLE
Update the isAvailable to return a boolean

### PR DESCRIPTION
**Pull request by Kikketer**
Supporting a use case where we would want to do a simple if check instead of using try/catch as the check:

```
if(await InAppBrowser.isAvailable()) {
  try { ... fire up the browser }
} else {
  ... use something else like Linker.openURL(
}
```

This is a breaking change since the `isAvailable` is no longer throwing an exception.  I also couldn't get the project to work so it goes untested.  Give it a shot and update/change as needed.

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Excellent mate!
Can you add you as a contributor from the README and update the version of the package please?👍

**Comment by jdnichollsc** [comment]
@Kikketer please let me know 👍

**Comment by Kikketer** [comment]
Yeah sorry been busy, I’ll get to it tonight. Thanks!

**Comment by jdnichollsc** [comment]
No problem mate, I undestersand 😅

**Pull request merged**
