### PR TITLE
fix(android): Fix error com.facebook.react.bridge.NoSuchKeyException

### PR DESCRIPTION
**Pull request by thuongtv-vn**
## PR Checklist

- [x ] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/main/CONTRIBUTING.md#pull-request-process.
- [ x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the new behavior?

Fixed: #284

### CODE REVIEW

**Review by reberthkss — APPROVED** [review]

**Review by phuongwd — APPROVED** [review]

**Comment by jdnichollsc** [comment]
@reberthkss did you try your approach first? 😅

**Comment by reberthkss** [comment]
@jdnichollsc yes, i'm react-native version `0.64.0`.

**Comment by jdnichollsc** [comment]
Oh ok, good to know 👍

**Comment by jdnichollsc** [comment]
@thuongtv-vn thanks for your collaboration! <3

**Comment by jdnichollsc** [comment]
@reberthkss Ok, we learned something new together! 😅

**Pull request merged**
