### PR TITLE
chore(android): replaced jCenter with maven

### PR DESCRIPTION
**Pull request by matteodanelli**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/main/CONTRIBUTING.md#pull-request-process.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [x] Tests for the changes are included

## What is the current behaviour?
jcenter is a dependdency 

## What is the new behavior?
Replaced jcenter with mavenCentral

Fixes/Implements/Closes #[317].

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Thanks for your awesome contribution mate! <3

**Comment by arcollector** [comment]
please merge to master

**Comment by jdnichollsc** [comment]
Let me try to do that today, I've been so busy, sorry for the delay 😅

**Comment by huditama** [comment]
Has this PR been merged to master already? Can't run or build app currently

**Comment by matteodanelli** [comment]
Not yet on main @huditama

**Pull request merged**
